[profile.default]
libs = ["lib", "dependencies"]

remappings = [
  "@zetachain/protocol-contracts/=lib/protocol-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[dependencies]

[rpc_endpoints]
zetachain_testnet = "https://rpc.ankr.com/zetachain_evm_athens_testnet"
base_sepolia = "https://sepolia.base.org"

